sim = bem_sim({ ...
    solid_bdry('surface_nodes',[0,0;1,0]),...
    solid_bdry('surface_nodes',[1,0;0.5,0.5;0,1]),...
    solid_bdry('surface_nodes',[0,1;0,0])
});

nodes = [0,0;1,0;0.5,0.5;0,1];


sim_spl = bem_sim({ ...
    solid_bdry('surface_nodes',[0,0;1,0],"bdry_interp_rule","spline"),...
    solid_bdry('surface_nodes',[1,0;0.5,0.5;0,1],"bdry_interp_rule","spline"),...
    solid_bdry('surface_nodes',[0,1;0,0],"bdry_interp_rule","spline")
});