sim_netcdf_manager
==================
Kentaro Hanson
:stem:

This class handles interfacing with a netCDF file.

== Usage

When running a simulation, it may be necessary to store data at multiple time steps. This is a netCDF file manager that works directly with link:bem_sim.html[`bem_sim`] objects.

Each manager has a specific file it works with, specified by `filename`. This is set in the <<constructor,constructor>> and should not be modified.

After each time step of the simulation (or between some other interval), <<save_time,`save_time()`>> can be called to save the state of the model into the netCDF file. A simple example would be to have the step method and the `save_time()` method in a loop.
[source,matlab]
----
manager = sim_netcdf_manager(filename,1); % overwrite=1: ensure new file
%assume simulator initial condition was already made
while sim.stepping.t < tmax
    sim = sim.step();
    manager.save_time(sim); % save after each time step
end
manager.flush_buffer(); % flush the buffer to the file
----

Accessing frames can be done through the <<get_sim,get_sim()>> or <<get_snapshot,get_snapshot()>> methods, for example, to play back the model and/or save it as an animation.
[source,matlab]
----
manager = sim_netcdf_manager(filename,0);
plotnum = 0;
figure(1);
for t=tmin:dt:tmax
    sim = manager.get_sim(t); % get closest to the given time
    sim.plot_FS(); % save the plot
    saveas(1,sprintf('dir/%s%d.png',figname,fignum));
    plotnum = plotnum+1;
end
----

== File format

NetCDF files handled by `sim_netcdf_manager` has its main data stored in groups, requiring the `netcdf4` format. Each group designates a different phase of the model, which can have different parameters, including different node counts. Globally, there are two variables:

.global variables
|===
|name |type |dimensions |Description
|phase_start
|double
|`index`
| An array of values representing the starting times for each phase. Data in each phase should be time-stamped at an equal or later time as the corresponding `phase_start` value.

|phase_end
|double
|`index`
| An array of values representing the ending times for each phase. Data in each phase should be time-stamped at an equal or earlier time as the corresponding `phase_start` value.
|===

Each group is specific a certain phase. The phase has specific values, specified in the group attributes, that are the same throughout the phase. These are

- `doublenode_indices` - a list of indices which are the double nodes

- `FS_start` - starting index of the free surface

- `FS_end` - final index of the free surface

- `interp_M` - the `M`-value of the link:bem_sim.html#interpolation[bem_sim.interpolation] struct.

- `interp_FS_M` - the `M`-value of the link:bem_sim.html#interpolation[bem_sim.interpolation_FS] struct.

- `interp_sliding_M` - the `M`-value of the link:bem_sim.html#interpolation[bem_sim.interpolation_sliding] struct.

- `timestep_method` - string of the time-stepping scheme, taking values in link:bem_sim.html#stepping_timestep_method[bem_sim.stepping.timestep_method].

Additionally, there are two dimensions:

- `t` - the time indices (unlimited).

- `N` - the number of nodes on the boundary.

The variables for each phase are as follows.

.group variables
|===
|name |type |dimensions |Description
|t
|double
|`t`
| the time stamps for each element of the time series.

|dt
|double
|`t`
| Time step size for each time.

|c_num
|double
|`t`
|Courant number for each time.

|x
|double
|`t` by `N`
|`x` coordinates of the boundary by node index at each time.

|z
|double
|`t` by `N`
|`z` coordinates of the boundary by node index at each time.

|phi
|double
|`t` by `N`
|phi values on the boundary by node index at each time.

|phi_n
|double
|`t` by `N`
|phi_n values on the boundary by node index at each time.

|energy
|double
|`t`
|total energy values at each time.

|volume
|double
|`t`
|total volume values at each time.

|mean_water_level
|double
|`t`
|mean water level values at each time.

|velocity_flux
|double
|`t`
|integral of phi_n over the boundary (should be zero, up to numerical error).
|===

== Properties

The `sim_netcdf_manager` object has the following properties:

- `filename` is the name of the netCDF file being referenced. This is set in the constructor and should not be modified.

- `buffer_size` is the number of snapshots permitted in the buffer. When this is full, the contents are flushed to the netCDF file.

- `buffer_index` is the index of the first empty space in the buffer. When appending to the buffer, snapshots are placed at this index. Instead of clearing the buffer when it is flushed, this value is set to `1`.

- `buffer` is the struct array containing the data at each snapshot.

- `phase_info` lists, by phase, the parameters for that phase. Instead of reading the netCDF file for <<is_compatible_with_phase,phase compatibility>> this struct array is referenced.

- `phase_bounds` stores the start and end times of each phase, matching `phase_start` and `phase_end`. Like `phase_info`, this can be referenced instead of needing to open the file.


== Methods

[#constructor]
=== Constructor
[source,matlab]
----
manager = sim_netcdf_manager(filename,overwrite);
----

Creates as new `sim_netcdf_manager` object for interfacing with the given file. If `overwrite` is set to true, then the file is cleared (if it exists). If a file does not exist, a new one is created. Issues may arise if a file that already exists was not created by a `sim_netcdf_manager` object.

When reading, make sure that `overwrite` is set to 0.

[#append_phase]
=== append_phase
[source,matlab]
----
manager.append_phase(sim);
----

Creates a new phase in the netCDF file, with parameters matching the given `bem_sim` object, passed as `sim`.

[#flush_buffer]
=== flush_buffer
[source,matlab]
----
manager.flush_buffer();
----

Flushes states from the buffer to the last phase. No compatibility checking is done in this method, so it should be perfomed before calling. This method also fails when no phase exists.

After flushing, the phase bounds (`phase_start` and `phase_end`) are updated accordingly.

[#get_sim]
=== get_sim
[source,matlab]
----
[sim, phase] = manager.get_sim(t);
----

Reads one state from the file that matches the given time the closest, returning it as a `bem_sim` object. Optionally, a phase index can be provided to only look at a given phase.

[source,matlab]
----
[snapshot, phase] = manager.get_snapshot(t,phase_index);
----

When `phase_index` is not given, or is invalid (less than 1 or greater than the total number of phases), then the entire file is searched.

[#get_snapshot]
=== get_snapshot
[source,matlab]
----
[snapshot, phase] = manager.get_snapshot(t);
----

Reads and returns one state from the file that matches the given time the closest. Optionally, a phase index can be provided to only look at a given phase.

[source,matlab]
----
[snapshot, phase] = manager.get_snapshot(t,phase_index);
----

When `phase_index` is not given, or is invalid (less than 1 or greater than the total number of phases), then the entire file is searched.

Within the searching domain, the state of the closest time to `t` is returned as a struct with the following values.
.group variables
|===
|name |type |Description
|t
|double
| the time value for this snapshot

|dt
|double
| Time step size for this step.

|c_num
|double
|Courant number for this step.

|x
|double array
|`x` coordinates of the boundary by node index.

|z
|double array
|`z` coordinates of the boundary by node index.

|phi
|double array
|phi values on the boundary by node index.

|phi_n
|double array
|phi_n values on the boundary by node index.

|energy
|double
|total energy value at this time step.

|volume
|double
|total volume at this time step.

|mean_water_level
|double
|mean water level values at this time step.

|velocity_flux
|double
|integral of phi_n over the boundary (should be zero, up to numerical error).
|===


[#is_compatible_with_phase]
=== is_compatible_with_phase
[source,matlab]
----
compatibility = manager.is_compatible_with_phase(sim,phase_index);
----

Checks if the given `bem_sim` object (passed as `sim`) is compatible with the given phase (specified by index as `phase_index`). Compatibility is determined by matching parameters in the group attributes and if the number of nodes match. If a `bem_sim` object is considered compatible with the last phase, then saving the state with <<save_time,+save_time()+>> will use the last phase. Otherwise, a new phase is appended.

[#save_time]
=== save_time
[source,matlab]
----
manager.save_time(sim);
----

Saves the current `bem_sim` object (passed as `sim`) state. Instead of immediately being written to the file, `save_time()` pushes the state onto a buffer. Only when the buffer is full, or if the phase changes (due to <<is_compatible_with_phase,incompatibility>>) is the buffer <<flush_buffer,flushed>>.

If the buffer is full, then it is flushed. If there is a phase
change, then a new phase is created and the buffer is flushed